apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # webapp_user
  POSTGRES_USER: d2ViYXBwX3VzZXI=
  # webapp_password
  POSTGRES_PASSWORD: d2ViYXBwX3Bhc3N3b3Jk
  # webapp_db
  POSTGRES_DB: d2ViYXBwX2Ri